### ISSUE TITLE
Disappearing calendar dates

### ISSUE THREAD

**Issue by enexusde** [mrzmyr/palila-app#1]
Having a empty tracking,
add a menstruation day to today and yesterday the menstruation is predicted.

That is good.

Problem: 

If I add tracking to the day before yesterday, the calendar-day of two days after tomorrow disappear and a gap remains.

Expected behaviour:

The calendar-day of two days after tomorrow remains visible.

**Comment by mrzmyr** [comment]
Hey @enexusde, I'm not actively maintaining this project anymore. However, thanks for your feedback!
